Recipes/BaremetalEnrtRecipe: avoid duplication of perf profiled cpus
LNST-project/lnst pull request #256
Opened 2022-10-06 15:42 UTC by jtluka

Description:  

If dev_intr_cpu and perf_tool_cpu contain the same cpus the LinuxPerf measurement would run perf profiler on these cpus twice, also writing to the same file at the same time, corrupting the data.

The two lists need to be aggregated and remove duplicates to avoid the conflict.

Fixes #255
  
Tests:  

RH internal job ids: ~~J:7083780~~ ~~J:7083775~~ J:7108529 (no override) J:7108533 (override)

Reviews:  

@olichtne @Kuba314 

Closes: #255

2022-10-06 15:52 UTC, Kuba314 submitted a review, later dismissed
LGTM

2022-10-06 17:01 UTC, jtluka commented
> I believe that this comes from the fact that the original implementation expected following format of the linuxperf_cpus: `[ [1,2,3], [4,5,6]]. However this does not make sense too much, it should be just list(int).

Hmm, maybe it does make sense.

The LinuxPerfMeasurement may profile various sets of CPUs at the same time. So the fix could be changing the linuxperf_cpus property to `[ list(set(dev_intr_cpu + perf_tool_cpu)) ]`

2022-10-06 17:14 UTC, jtluka commented
Although this would fix the issue, it's not the intended use.

We want to be able to profile both the cpus used for interrupts as well as cpus used for iperf independently. So, we'll likely need to add some logic on creating the sets.

For the simplest case, when we ping IRQs to one cpu and iperf to another cpu, we just need to check if they're equal:
* dev_intr_cpu=[0] perf_tool_cpu=[5] -> linuxperf_cpus=[ [0], [5] ]
* dev_intr_cpu=[5] perf_tool_cpu=[5] -> linuxperf_cpus=[ [5] ]

For more complex scenarios, like parallel iperf testing, this would get complicated:
* dev_intr_cpu=[0,1,2,3] perf_tool_cpu=[0,1,2,3] -> linuxperf_cpus=[ [0,1,2,3] ]
* dev_intr_cpu=[0,1,2,3] perf_tool_cpu=[4,5,6,7] -> linuxperf_cpus=[ [0,1,2,3], [4,5,6,7 ]

So maybe just check that if the lists are same, then just use only one, otherwise use both?

2022-10-06 18:04 UTC, Kuba314 commented
@jtluka why don't we just do `set([tuple(dev_intr_cpu), tuple(perf_tool_cpu)])`? This will not work correctly only if both sets of CPUs intersect only in *some* cpus. What should we do then? Either we decide to run `perf` twice on the intersected CPUs, or we run `perf` only once, but then the results would be only in one of the two files.

2022-10-07 07:13 UTC, jtluka commented
@Kuba314 that's interesting idea. I've checked this with two common scenarios and it works perfectly. Thanks for suggestion.

2022-10-10 11:58 UTC, olichtne commented
wouldn't it be easier to keep the `linuxperf_cpus=[[1, 2], [1, 2]]` logic (so allow duplicated cpu sets) but change the way we generate `LinuxPerf` classes so that each instance writes to a different file that doesn't create name conflicts?

this way you don't have to come up with a way of "what duplicate detection" method works exactly how we want it but instead accept that you may create two captures that are basically the same but since they don't conflict with each other then it shouldn't be a problem?

2022-10-10 12:46 UTC, jtluka commented
> wouldn't it be easier to keep the linuxperf_cpus=[[1, 2], [1, 2]] logic (so allow duplicated cpu sets) but change the way we generate LinuxPerf classes so that each instance writes to a different file that doesn't create name conflicts?

I'm a bit worried about additional performance hit. Of course, if we're profiliing the performance measurements are very likely to be off, but not sure if this would skew the measurements more.

On the other hand, your proposal is more generic and "safe" in a sense that we don't introduce additional issues that we would have to fix later.

2022-10-10 15:52 UTC, jtluka commented
@olichtne @Kuba314 I've force pushed another implementation of the fix for this issue, please review.

2022-10-12 11:06 UTC, jtluka commented
I also had an idea, that in some cases it would be useful to override this with a recipe parameter. That way the user can simply specify `linuxperf_cpus=[ [0,1], [3,4] ]`. So, the value would not be determined on what the `dev_intr_cpu`/`perf_tool_cpu` values are.

2022-10-12 11:45 UTC, olichtne commented
> override this with a recipe parameter

yeah i think that can make sense in situations where you may want to profile all cpus for example. i think there may be a slight problem with this in case the matched machines don't have an equal number of cpu cores.

2022-10-13 15:17 UTC, jtluka commented
I've pushed additional changes that makes possible to override the profiled cpus with a recipe parameter.

Here's a summary:
* to avoid overwriting files generated by perf profiler, the filenames include the index of the cpu group in the `linuxperf_cpus` cpu group list
* the `BaremetalEnrtRecipe.linuxperf_cpus` property remains unchanged
* a new `linuxperf_cpus_override` recipe parameter is provided by `LinuxPerfMeasurementGenerator`, that can be used to override the `linuxperf_cpus` property defined by a recipe derived from `BaremetalEnrtRecipe`
  * this can be used also when the recipe does not have the `linuxperf_cpus` defined
* there's a TODO included where it makes sense to do perf profiliing without any cpus specified, however that would require addtional changes in LinuxPerfMeasurement - to avoid snowball effect, I'll create a separate issue for this - for now, if `do_linuxperf_measurement=True` and set of cpus to be profiled turns out to be empty, that would raise an Exception

2022-10-13 15:24 UTC, jtluka commented on lnst/Recipes/ENRT/MeasurementGenerators/LinuxPerfMeasurementGenerator.py
> +                "Cannot profile empty list of cpus when do_linuxperf_measurement parameter is specified"
This is misleading. The `do_linuxperf_measurement` may be both True and False.

2022-10-13 15:26 UTC, jtluka commented
New test jobs J:7108529 (no override) J:7108533 (override)

2022-10-13 16:01 UTC, Kuba314 requested changes

2022-10-13 16:01 UTC, Kuba314 commented on lnst/Recipes/ENRT/MeasurementGenerators/LinuxPerfMeasurementGenerator.py
> +                profiled_cpu_groups = []
You can replace this with `getattr`:
```suggestion
            profiled_cpu_groups = getattr(self, "linuxperf_cpus", [])
```

2022-10-14 06:41 UTC, jtluka commented on lnst/RecipeCommon/Perf/Measurements/LinuxPerfMeasurement.py
> +                yield (cpu_list_id, host, cpu_list)
Ok, will change that.

2022-10-14 06:42 UTC, jtluka commented on lnst/Recipes/ENRT/MeasurementGenerators/LinuxPerfMeasurementGenerator.py
> +        profiled_cpu_groups: list(list(int)) = []
Good catch. Will fix that, thanks.

2022-10-14 06:46 UTC, jtluka commented on lnst/Recipes/ENRT/MeasurementGenerators/LinuxPerfMeasurementGenerator.py
> +                profiled_cpu_groups = []
Yeah makes sense.

2022-10-14 06:54 UTC, jtluka commented on lnst/RecipeCommon/Perf/Measurements/LinuxPerfMeasurement.py
> +                yield (cpu_list_id, host, cpu_list)
Fixed.

2022-10-14 06:56 UTC, jtluka commented
New test jobs: J:7111484 J:7111482

2022-10-14 06:59 UTC, jtluka commented on lnst/Recipes/ENRT/MeasurementGenerators/LinuxPerfMeasurementGenerator.py
> +                "Cannot profile empty list of cpus when do_linuxperf_measurement parameter is specified"
Fixed.

2022-10-14 09:32 UTC, jtluka commented
> New test jobs: J:7111484 J:7111482

The jobs completed and the new file names were used correctly both with and without override.

2022-10-17 11:24 UTC, olichtne approved these changes
looks good to me.

2022-10-17 11:34 UTC, enhaut approved these changes

2022-10-17 13:51 UTC, Kuba314 approved these changes
LGTM now

2022-10-17 15:52 UTC, merged