Add vxlan hw tc offload
LNST-project/lnst pull request #342
Opened 2023-10-30 10:02 UTC by jtluka

### Description

This pull request adds new test SRIOVNetnsVxlanTcRecipe. To avoid code duplication I moved most of the functionality to
a new base class BaseSRIOVNetnsTcRecipe and updated the existing SRIOVNetnsTcRecipe to use the base class.

The new base class provides two common methods that the derived class overrides:
* `add_tc_filter_rules()` (must be defined by every derived class)
* `add_network_layers()` (optional, to define additional network stacks, for example tunnels between VFs)

### Tests

J:8496033

### Reviews

@Axonis @olichtne

2023-11-01 12:57 UTC, olichtne commented on lnst/Recipes/ENRT/SRIOVNetnsVxlanTcRecipe.py
> +            f"action tunnel_key set src_ip {host1.eth0.ips_filter(family=AF_INET)[0]} dst_ip {host2.eth0.ips_filter(family=AF_INET)[0]} "
and here

2023-11-01 12:57 UTC, olichtne commented on lnst/Recipes/ENRT/SRIOVNetnsVxlanTcRecipe.py
> +            f"action tunnel_key set src_ip {host1.eth0.ips_filter(family=AF_INET)[0]} dst_ip {host2.eth0.ips_filter(family=AF_INET)[0]} "
and the same for the next commands as well

2023-11-01 13:00 UTC, olichtne requested changes
mostly ok, but i'd like to now keep consistency with avoiding to use the `ip_filters` method for using followup configuration commands. this can lead to non-deterministic behaviour in case of issues with configuration.

other than this i'll also check the test runs but i assume if everything is working that this should be ok.

2023-11-01 13:06 UTC, olichtne commented
one more question the test you link to ` J:8496862 (with geneve)` has 3*mlx5_core_25g tests, 3*mlx5_cx6dx tests but only 1*ice test, is this intentional?

2023-11-01 14:11 UTC, jtluka commented
> one more question the test you link to ` J:8496862 (with geneve)` has 3_mlx5_core_25g tests, 3_mlx5_cx6dx tests but only 1*ice test, is this intentional?

yes, ice does not have hw offload for encap/decapsulation, so I do not plan to add these in the test set.

2023-11-01 14:57 UTC, jtluka commented on lnst/Recipes/ENRT/SRIOVNetnsVxlanTcRecipe.py
> +                remote=host2.eth0.ips_filter(**ip_filter)[0] if host == host1 else host1.eth0.ips_filter(**ip_filter)[0],
I'll update this. Thanks.

2023-11-01 16:08 UTC, jtluka commented on lnst/Recipes/ENRT/SRIOVNetnsVxlanTcRecipe.py
> +                remote=host2.eth0.ips_filter(**ip_filter)[0] if host == host1 else host1.eth0.ips_filter(**ip_filter)[0],
Should be fixed now.

2023-11-01 16:08 UTC, jtluka commented on lnst/Recipes/ENRT/SRIOVNetnsVxlanTcRecipe.py
> +            f"action tunnel_key set src_ip {host1.eth0.ips_filter(family=AF_INET)[0]} dst_ip {host2.eth0.ips_filter(family=AF_INET)[0]} "
Should be fixed now.

2023-11-01 16:08 UTC, jtluka commented on lnst/Recipes/ENRT/SRIOVNetnsGeneveTcRecipe.py
> +                remote=host2.eth0.ips_filter(**ip_filter)[0] if host == host1 else host1.eth0.ips_filter(**ip_filter)[0],
Should be fixed now.

2023-11-02 08:20 UTC, olichtne approved these changes

2023-11-02 08:41 UTC, merged