ContainerPoolManager: add netavark support
LNST-project/lnst pull request #378
Opened 2024-09-16 11:29 UTC by jtluka

### Description

With podman5+ the CNI network backend support is removed, with netavark being the default network plugin.

This adds support for netavark network backend and changes the ContainerPoolManager to use it as default.

The CNI backend support is kept and user can force LNST to use it by `ContainerPoolManager(network_plugin='cni')`.

### Tests

Tested on Fedora40 with podman-5.2.2-1.fc40.x86_64

### Reviews

@olichtne @enhaut

2024-09-16 11:31 UTC, jtluka commented
I will update the container documentation.

2024-09-16 11:40 UTC, olichtne requested changes
just a minor comment, otherwise this looks ok.

not sure if github ci needs to be (or should be) somehow updated as that also runs tests in a container environment.

2024-09-16 11:40 UTC, olichtne commented on lnst/Controller/ContainerPoolManager.py
> +    def _create_network(self, network_name: str, plugin: str="netavark"):
you probably don't need the default value in this private method since you already define the default in `__init__`

2024-09-16 11:53 UTC, jtluka commented
> just a minor comment, otherwise this looks ok.
> 
> not sure if github ci needs to be (or should be) somehow updated as that also runs tests in a container environment.

I expected some issues with CI and I will take a look at it.

2024-09-16 12:21 UTC, jtluka commented on lnst/Controller/ContainerPoolManager.py
> +            self._podman_client.networks.create(
It is using 'bridge' driver by default. It picks up a IP address from DHCP on the host's network. At least this is my observation.

2024-09-16 12:33 UTC, jtluka commented on lnst/Controller/ContainerPoolManager.py
> +            self._podman_client.networks.create(
Ah sorry ... this is for the pod default connection. I believe there should be no interference.

2024-09-16 12:36 UTC, jtluka commented on lnst/Controller/ContainerPoolManager.py
> +            self._podman_client.networks.create(
But probably we could use "inetrnal" parameter for the network.

```
internal (bool) – Restrict external access to the network.
```

2024-09-16 12:37 UTC, jtluka commented on lnst/Controller/ContainerPoolManager.py
> +            self._podman_client.networks.create(
Ah, it's already set in the patch.

2024-09-16 16:18 UTC, jtluka commented on lnst/Controller/ContainerPoolManager.py
> +            self._podman_client.networks.create(
So, here's my further analysis that proves that nothing else is required at this point.

Network inspection:
```
# podman network inspect lnst_container_net_net1
[
     {
          "name": "lnst_container_net_net1",
          "id": "39386719320c57e567a38db5d46c6844d6434c60f910287e36aafd4c0cf58222",
          "driver": "bridge",
          "network_interface": "podman1",
          "created": "2024-09-16T18:13:54.889768776+02:00",
          "subnets": [
               {
                    "subnet": "10.89.0.0/24"
               },
               {
                    "subnet": "fd62:ad23:f57c:7aa3::/64"
               }
          ],
          "ipv6_enabled": true,
          "internal": true,
          "dns_enabled": false,
          "ipam_options": {
               "driver": "host-local"
          },
          "containers": {
               "749c69d3bee08e2599e0fec78eb53145c3a828a2f57ef05502f0fc754c733c14": {
                    "name": "musing_wu",
                    "interfaces": {
                         "eth1": {
                              "subnets": [
                                   {
                                        "ipnet": "10.89.0.1/24"
                                   },
                                   {
                                        "ipnet": "fd62:ad23:f57c:7aa3::1/64"
                                   }
                              ],
                              "mac_address": "da:49:83:e8:07:8a"
                         }
                    }
               },
               "e3118e66b7f28ab5131563f7afe416b11e8b7cc81437f7d73aab2ac37e948054": {
                    "name": "jolly_pare",
                    "interfaces": {
                         "eth1": {
                              "subnets": [
                                   {
                                        "ipnet": "10.89.0.2/24"
                                   },
                                   {
                                        "ipnet": "fd62:ad23:f57c:7aa3::2/64"
                                   }
                              ],
                              "mac_address": "4a:f7:79:9b:99:d2"
                         }
                    }
               }
          }
     }
]
```

Here, the most important is the "subnets" that shows that the network has an address space allocated,
however the addresses are not assigned unless they're requested with a DHCP.

2024-09-16 17:00 UTC, jtluka commented
I've added automatic detection of network backend, so updates to github CI should not be necessary.

2024-09-16 17:29 UTC, jtluka commented
CI will require the patch anyway.

I've tested automatic backend detection on Fedora39 + cni and container setup works fine.

2024-09-17 11:06 UTC, olichtne submitted a review, later dismissed
looks ok to me now.

2024-09-17 11:18 UTC, jtluka commented on lnst/Controller/ContainerPoolManager.py
> +            self._podman_client.networks.create(
This was a bad assumption. The containers still get an IP address:
```
[root@machine1 /]# ip -4 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0@if16: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000 link-netnsid 0
    inet 10.88.0.6/16 brd 10.88.255.255 scope global eth0
       valid_lft forever preferred_lft forever
3: eth1@if18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000 link-netnsid 0
    inet 10.89.0.1/24 brd 10.89.0.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet 192.168.1.1/24 scope global eth1
       valid_lft forever preferred_lft forever

```

2024-09-17 12:51 UTC, jtluka commented on lnst/Controller/ContainerPoolManager.py
> +            self._podman_client.networks.create(
This looks like a bug in podman-python api.

I was able to used ipam driver 'none' with fixed podman api code and no IP address was assigned to the interfaces in created network.

```diff
diff --git a/podman/domain/networks_manager.py b/podman/domain/networks_manager.py
index 6f33202..3a2100a 100644
--- a/podman/domain/networks_manager.py
+++ b/podman/domain/networks_manager.py
@@ -79,6 +79,11 @@ class NetworksManager(Manager):
         if "Config" not in ipam:
             return
 
+        if "Driver" in ipam:
+            data["ipam_options"] = {
+                "driver": ipam["Driver"]
+            }
+
         data["subnets"] = []
         for cfg in ipam["Config"]:
             subnet = {
```

Generated network now has:
```
# sudo podman network inspect lnst_container_net_net1
[
     {
          "name": "lnst_container_net_net1",
          "id": "45ef23430893e413e1365ce32e65f03d5a9b68e0c5239e3a173845f65dd2a588",
          "driver": "bridge",
          "network_interface": "podman1",
          "created": "2024-09-17T14:46:38.771124038+02:00",
          "ipv6_enabled": true,
          "internal": true,
          "dns_enabled": false,
          "ipam_options": {
               "driver": "none"
          },
          "containers": {
               "6bb7ce22fa585e18527ec93b4bd1306f10a6e5a0a609c6fed7c7cec62fda29e9": {
                    "name": "intelligent_turing",
                    "interfaces": {
                         "eth1": {
                              "mac_address": "66:0f:37:e5:26:60"
                         }
                    }
               },
               "84ece9c712c375d68896244d9f8d8d00a7faa0df8c610accc5ce6aeb7b404f44": {
                    "name": "naughty_pasteur",
                    "interfaces": {
                         "eth1": {
                              "mac_address": "32:7a:a2:b1:25:2d"
                         }
                    }
               }
          }
     }
]
```

2024-09-17 13:10 UTC, jtluka commented on lnst/Controller/ContainerPoolManager.py
> +            self._podman_client.networks.create(
Posted a patch for podman-py https://github.com/containers/podman-py/pull/429

2024-09-17 13:19 UTC, jtluka commented on lnst/Controller/ContainerPoolManager.py
> +            self._podman_client.networks.create(
I've updated this MR to use the IPAMConfig.driver

2024-09-18 07:40 UTC, jtluka commented on lnst/Controller/ContainerPoolManager.py
> +            self._podman_client.networks.create(
As the current solution works and is not dependent on the podman change I'm resolving this and will followup with poetry update once the fix is merged.

2024-09-18 08:02 UTC, enhaut approved these changes

2024-09-18 08:19 UTC, olichtne approved these changes

2024-09-18 08:33 UTC, merged