HOTFIX: XDPBenchResults: split inheritance tree
LNST-project/lnst pull request #385
Opened 2024-10-24 11:29 UTC by enhaut

### Description

`XDPBenchMeasurements` results used to use `FlowMeasurementResults` as a base class overriding some of its methods because xdp-bench tool doesn't measure CPU usage and so `FlowMeasurementResults`'s CPU metrics were set to `None`.

Recent changes from [0] now expects `FlowMeasurementResults` to use both perf and CPU results. Especially
`.{start,end}_timestamp` properties expect CPU metrics to be set and if not, it crashes since not using CPU metrics is "masked" by setting `None` instead of regular result containers.

[0] https://github.com/LNST-project/lnst/pull/382

### Tests
XDP drop ipv4+ipv6 test in `J:10094508`

without fix, running any xdp recipe crashed on:
```python
Traceback (most recent call last):
  File "./do-my-test", line 35, in main
    ctl.run(recipe, multimatch=bool(params.get("MULTIMATCH", False)))
  File "/lnst/lib/python3.9/site-packages/lnst/Controller/Controller.py", line 172, in run
    recipe.test()
  File "/lnst/lib/python3.9/site-packages/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 210, in test
    self.do_tests(recipe_config)
  File "/lnst/lib/python3.9/site-packages/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 332, in do_tests
    self.do_perf_tests(recipe_config)
  File "/lnst/lib/python3.9/site-packages/lnst/Recipes/ENRT/BaseEnrtRecipe.py", line 358, in do_perf_tests
    self.perf_report_and_evaluate(result)
  File "/lnst/lib/python3.9/site-packages/lnst/RecipeCommon/Perf/Recipe.py", line 207, in perf_report_and_evaluate
    aligned_results = results.time_aligned_results
  File "/lnst/lib/python3.9/site-packages/lnst/RecipeCommon/Perf/Recipe.py", line 127, in time_aligned_results
    real_times = self._get_measurement_timestamps(iteration_results_group)
  File "/lnst/lib/python3.9/site-packages/lnst/RecipeCommon/Perf/Recipe.py", line 112, in _get_measurement_timestamps
    return flows[-1].warmup_end, flows[-1].warmdown_start
  File "/lnst/lib/python3.9/site-packages/lnst/RecipeCommon/Perf/Measurements/Results/FlowMeasurementResults.py", line 87, in warmup_end
    return self.start_timestamp+self.warmup_duration
  File "/lnst/lib/python3.9/site-packages/lnst/RecipeCommon/Perf/Measurements/Results/FlowMeasurementResults.py", line 68, in start_timestamp
    self.generator_cpu_stats.start_timestamp,
AttributeError: 'NoneType' object has no attribute 'start_timestamp'
```

Now it works as expected.

2024-10-24 11:47 UTC, jtluka commented on lnst/RecipeCommon/Perf/Measurements/Results/XDPBenchMeasurementResults.py
> +class XDPBenchMeasurementResults(BaseMeasurementResults):
Can't we keep inheriting from FlowMeasurementResults and only override problematic properties that seem to be `start_timestamp` and `end_timestamp`?

2024-10-24 11:55 UTC, olichtne requested changes
I think changing the base class type makes it so that the measurement results aren't properly exported via the Json run summary formatter and so the type should be added there as well.

The test job shows:
```
    {
        "result": "PASS",
        "type": "measurement",
        "measurement_type": "cpu",
        "data": {
            "utilization": 658.9386350727488
        }
    },
    {
        "result": "PASS",
        "type": "measurement",
        "measurement_type": "cpu",
        "data": {
            "utilization": 86.08423280166635
        }
    },
    {
        "result": "PASS",
        "type": "unknown",
        "description": "Flow(\n    type=xdp,\n    generator=Host(machine_id=host1),\n    generator_bind=192.168.101.1,\n    generator_nic=Device(machine=host1, id=eth0, name=eno12399, ifindex=4),\n    generator_port=12000,\n    receiver=Host(machine_id=host2),\n    receiver_bind=192.168.101.2,\n    receiver_nic=Device(machine=host2, id=eth0, name=eno12399, ifindex=4),\n    receiver_port=12000,\n    msg_size=60,\n    duration=60,\n    parallel_streams=1,\n    generator_cpupin=[0, 2, 4, 6, 8],\n    receiver_cpupin=[0, 2, 4, 6, 8],\n    aggregated_flow=False\n    warmup_duration=3,\n)\nGenerator generated (generator_results): 37,172,469.218145 packets per second.\nReceiver processed (receiver_results): 37,149,679.712138 packets per second."
    },
```

where the `unknown` result is the xdp measurement result

2024-10-25 14:03 UTC, jtluka commented on lnst/RecipeCommon/Perf/Measurements/Results/XDPBenchMeasurementResults.py
> +class XDPBenchMeasurementResults(BaseMeasurementResults):
Ok, resolving.

2024-10-30 11:16 UTC, olichtne approved these changes

2024-10-30 11:16 UTC, merged